import Header from "@/components/Header";
import { Lato } from "next/font/google";
import "../globals.css";
import Footer from "@/components/Footer";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section className="max-w-4xl mx-auto p-6">
      <Header />
      {children}
      <Footer />
    </section>
  );
}
