import Header from "@/components/Header";
import { Lato } from "next/font/google";
import "../../globals.css";
import { Toaster } from "react-hot-toast";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>
      <Toaster position="bottom-center" />
      {children}
    </main>
  );
}
